### ISSUE TITLE
Add Shooting Settings screen 

### ISSUE THREAD

**Issue by jcasman** [caitlynbakery/theta_x_bloc#3]
Please add a new button to the existing screen. 

1. A button for turning off the LCD screen. This is an options setting. Set the value to "app" - https://api.ricoh/docs/theta-web-api-v2.1/options/_camera_control_source/

Also, please give this page the name "Main"

Please add a new "Shooting Settings" page. It will be another screen in the app. It will be listed in the hamburger menu, so you can navigate between the two screens.

On the new page, please add several buttons.

1. Please add a way to set to video or image mode. Image has two settings: 5.5K and 11K. Video has two settings: 8K 2fps and 8K 5fps. 

https://api.ricoh/docs/theta-web-api-v2.1/options/file_format/

Parameters for image
{“type”: “jpeg”,”width”: 11008,”height”: 5504}
{“type”: “jpeg”,”width”: 5504,”height”: 2752}

Parameters for video
{“type”: “mp4”,”width”: 7680,”height”: 3840, “_codec”: “H.264/MPEG-4 AVC”, “_frameRate”: 5}
{“type”: “mp4”,”width”: 7680,”height”: 3840, “_codec”: “H.264/MPEG-4 AVC”, “_frameRate”: 2}

**Comment by caitlynbakery** [comment]
Ok, I'll start working on it. Thanks!
